cabinet_chat:
    resource: "@CabinetChatBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: _cabinet_index
        permanent: true