parameters:
#    cabinet_chat.example.class: Cabinet\ChatBundle\Example

services:
#    cabinet_chat.example:
#        class: %cabinet_chat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    cabinet.twig.cabinet_extension:
        class: Cabinet\ChatBundle\Twig\CabinetExtension
        arguments:
              em: "@doctrine"
              service_container: "@service_container"
        tags:
            - { name: twig.extension }